USER seluser

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY entry_point.sh /opt/bin/entry_point.sh

RUN echo 1 > /tmp/standalone_ok

EXPOSE 4444
