USER seluser

#======================
# Scripts to run WARSAW
#======================

RUN  sudo mkdir -p /opt/warsaw \
  && sudo chown seluser:seluser /opt/warsaw \
  && wget --no-verbose https://cloud.gastecnologia.com.br/bb/downloads/ws/warsaw_setup64.deb -O /opt/warsaw/warsaw_setup64.deb

RUN echo 1 > /tmp/warsaw_ok

EXPOSE 4444
